### ISSUE TITLE
commit: 6c1ec9a generated this bug [Illuminate\Contracts\Encryption\DecryptException]   The payload is invalid.

### ISSUE THREAD

**Issue by XavierTecBr** [tymondesigns/jwt-auth#1372]
commit: 6c1ec9a generated this bug [Illuminate\Contracts\Encryption\DecryptException]   The payload is invalid.

when i running php artisan migrate.

my solution was specified the commit on composer json. "tymon/jwt-auth": "dev-develop#b17f573",

**Comment by koenhoeijmakers** [comment]
I have already addressed this issue in PR [#1371](https://github.com/tymondesigns/jwt-auth/pull/1371)

**Comment by XavierTecBr** [comment]
The error was on my migration, i did in a new branch, that dind't has cookie, see:

i beleave to be this method, bellow: 
public function insertSuperUser()
    {

        $this->user = new App\Models\User();

        $this->user->fill([
            'name' => 'Admin',
            'email' => 'super@company.com.br',
            'password' => bcrypt('secret'),
            'remember_token' => str_random(10)
        ]);
        $this->user->save();
    }

**Comment by koenhoeijmakers** [comment]
Ah my bad, but the error was coming from the same part :)

**Comment by Broutard** [comment]
Why it is closed ? Issue is still valid in the last "^1.0@dev" (fixed to switching to "^1.0@RC").

The bug was introduced in https://github.com/tymondesigns/jwt-auth/commit/eb5cd7eb7be867f740546596f3a16b5806106890 

Oh, sorry I have miss the new config option `decrypt_cookies`, but I don't understant : 
my cookie is crypted by default (not setted in EncryptCookies middleware $except), but I must set the "decrypt_cookies" config to `false` to avoid "The payload is invalid." error
