### ISSUE TITLE
 Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, null given

### ISSUE THREAD

**Issue by sulemankhann** [tymondesigns/jwt-auth#1729]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 5.7
| Package version   | 11.0.0-rc.3
| PHP version       |  7.x.y

### Steps to reproduce
Tell us how to reproduce this issue.
After Pushing code to live server and generating jwt key and clearing config cache. I get  Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, null given, error

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by sulemankhann** [comment]
Error occurred because of Config Cached and i know that and clear cache multiple time with 
php artisan config:clear but no luck but after running php artisan config:cache command i recached config file and error was gone :-)

**Comment by ghost** [comment]
voy a volverme loco, no consigo una solucion

**Comment by SelectOne** [comment]
Thanks

**Comment by enzonotario** [comment]
Run `php artisan jwt:secret`, that works for me

**Comment by jbnv** [comment]
I ran `php artisan jwt:secret` but I'm still getting the error.

```
Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, null given, called in vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 3 passed to Lcobucci\\JWT\\Signer\\Hmac::doVerify() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given, called in vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 44 at vendor/lcobucci/jwt/src/Signer/Hmac.php:29)
[stacktrace]
#0 vendor/lcobucci/jwt/src/Signer/BaseSigner.php(44): Lcobucci\\JWT\\Signer\\Hmac->doVerify('-\\x9Ek\\xD5@\\xD3_Y\\xB3%A\\xB0+\
\\xD6...', 'eyJ0eXAiOiJKV1Q...', NULL)
#1 vendor/lcobucci/jwt/src/Signature.php(47): Lcobucci\\JWT\\Signer\\BaseSigner->verify('-\\x9Ek\\xD5@\\xD3_Y\\xB3%A\\xB0+\
\\xD6...', 'eyJ0eXAiOiJKV1Q...', NULL)
#2 vendor/lcobucci/jwt/src/Token.php(201): Lcobucci\\JWT\\Signature->verify(Object(Lcobucci\\JWT\\Signer\\Hmac\\Sha256), 'eyJ0eXAiOiJKV1Q...', NULL)
#3 vendor/tymon/jwt-auth/src/Providers/JWT/Lcobucci.php(136): Lcobucci\\JWT\\Token->verify(Object(Lcobucci\\JWT\\Signer\\Hmac\\Sha256), NULL)
#4 vendor/tymon/jwt-auth/src/Manager.php(101): Tymon\\JWTAuth\\Providers\\JWT\\Lcobucci->decode('eyJ0eXAiOiJKV1Q...')
#5 vendor/tymon/jwt-auth/src/JWT.php(200): Tymon\\JWTAuth\\Manager->decode(Object(Tymon\\JWTAuth\\Token))
#6 vendor/tymon/jwt-auth/src/JWT.php(136): Tymon\\JWTAuth\\JWT->getPayload()
#7 vendor/tymon/jwt-auth/src/JWT.php(149): Tymon\\JWTAuth\\JWT->checkOrFail()
#8 vendor/tymon/jwt-auth/src/JWTGuard.php(79): Tymon\\JWTAuth\\JWT->check(true)
#9 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(297): Tymon\\JWTAuth\\JWTGuard->user()
#10 vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Auth\\AuthManager->__call('user', Array)
#11 app/Http/Controllers/AuthController.php(45): Illuminate\\Support\\Facades\\Facade::__callStatic('user', Array)
...
```

**Comment by thiagolinoz** [comment]
php artisan jwt:secret worked for me too. it set a key

**Comment by dt-jegomez** [comment]
estoy trabajando en Laragon.  con servidor apache y e realizado php artisan jwt:secret y php artisan config:cache y no e optenido solucion 
-----------------------------------------------
I am working in Laragon. with apache server and done php artisan jwt: secret and php artisan config: cache and no and opted solution

**Comment by sahsuraj** [comment]
awesome, its worked using below command

php artisan jwt:secret

**Comment by bosz** [comment]
> Run `php artisan jwt:secret`, that works for me

Awesome `php artisan jwt:secret` worked for me. Thanks

**Comment by praditha** [comment]
This is what worked for me:
`php artisan jwt:secret`
`php artisan config:clear`
`php artisan config:cache`

**Comment by rossjcooper** [comment]
If you get this error in your CI tools when running tests be sure to set `JWT_SECRET` to something in `phpunit.xml`

```xml
 <server name="JWT_SECRET" value="..."/>
```

**Comment by Nataanthoni** [comment]
I came across this error when I deployed my application after testing and everything else worked well on the local server.

I noticed the following;

 - It's possible that you are getting this error when you uploaded the applications before implementing the JWT and re-uploaded directly via the Cpanel upload without reuploading the .env file.

- if this is the case, the simplest way to solve this is my merely adding the JWT: key in your .env file (at the bottom) eg

JWT_SECRET=roCZauuldMpw5i4039393939393372y98bEWumqd9ls7Uk8DEpr0gIZ6WIWB

Hope this helps :)

**Comment by viniciusmelocodes** [comment]
This is what worked for me:
`php artisan jwt:secret`
`php artisan config:clear`
`php artisan config:cache`
`sudo chmod 777 -Rf storage/`

**Comment by mhlanga-joseph** [comment]
@Nataanthoni answer worked for me. Unfortunately, I had not set a JWT_SECRET in my .env. My bad!

**Comment by blessingk** [comment]
This is what worked for me:
```
php artisan jwt:secret
php artisan config:clear
php artisan config:cache
```

**Comment by gentritabazi** [comment]
Lumen does not have **config:clear** or **config:cache** artisan command.

This error is still present in Lumen.

**Comment by blessingk** [comment]
l think its for laravel only

**Comment by Arup-paul** [comment]
`php artisan jwt:secret

work for me. Thanks
`

**Comment by Arup-paul** [comment]
> `php artisan jwt:secret`
Work for me. Thanks

**Comment by vijaysharma0757** [comment]
`php artisan jwt:secret`

Worked for me, Thanks.

**Comment by priya-concetto** [comment]
> Run `php artisan jwt:secret`, that works for me

it works for me

**Comment by bydavid1** [comment]
Estaba probando en heroku y me funcionó:

Obtener el secret key

`heroku run bash`
`php artisan jwt:secret`
`php artisan config:clear`
`php artisan config:cache`

Luego agregarla como variable (fuera de heroku bash)

`heroku config:add JWT_SECRET={your jwt secret key}`

**Comment by DevDast** [comment]
> Error occurred because of Config Cached and i know that and clear cache multiple time with
> php artisan config:clear but no luck but after running php artisan config:cache command i recached config file and error was gone :-)

Just 
```
php artisan config:cache
```
Worked for me, Big Thanks.

**Comment by iamyasiramjad** [comment]
Run - php artisan jwt:secret - that's initially not work for me. then after i use this - php artisan config:cache - now its working.

**Comment by Sunnepah** [comment]
This works for me
```
php artisan jwt:secret
php artisan config:cache
```

**Comment by riteshsingh1** [comment]
good work for me

**Comment by bosz** [comment]
Thanks

**Comment by ibrahimBougaoua** [comment]
this work for me
php artisan key:generate
php artisan jwt:secret
php artisan cache:clear
php artisan config:clear

**Comment by floflo711** [comment]
> Lumen

Im using Lumen v8.x

I also have the error. I tried php artisan jwt:secret
php artisan cache:clear

i put the v3.3.3 of lcobucci in composer + composer update


error still pop in the console log from time to time

**Comment by HamadaSalah** [comment]
You Don't write JWT_SECRET in .env File You Can Run 
`php artisan jwt:secret`
and then clear cache
