### ISSUE TITLE
Class jwt.auth does not exist

### ISSUE THREAD

**Issue by Destreyf** [tymondesigns/jwt-auth#290]
I just updated my Laravel instance and had to roll some stuff back to get it upgraded, once i finished the upgrade everything seems to be working except when i use a route that is in a group with a middleware of jwt.auth assigned, i am not sure if i broke something in the process of rolling back and forward or if there's something incompatible since the new 5.1.11 upgrade.

I am just dumping this info here so you can see what i have, this **was** previously working before i attempted an upgrade of Laravel.

Package|Version
-------|-------
asm89/stack-cors|0.2.1
aws/aws-sdk-php|3.8.0
barryvdh/laravel-cors|v0.7.2
classpreloader/classpreloader|2.0.0
danielstjules/stringy|1.10.0
dnoegel/php-xdg-base-dir|0.1
doctrine/inflector|v1.0.1
doctrine/instantiator|1.0.5
fzaninotto/faker|v1.5.0
guzzlehttp/guzzle|6.1.0
guzzlehttp/promises|1.0.2
guzzlehttp/psr7|1.2.0
hamcrest/hamcrest-php|v1.2.2
jakub-onderka/php-console-color|0.1
jakub-onderka/php-console-highlighter|v0.3.2
jeremeamia/SuperClosure|2.1.0
laravel/framework|v5.1.20
laravelcollective/html|v5.1.6
league/flysystem|1.0.15
league/flysystem-aws-s3-v3|1.0.6
league/fractal|0.12.0
mockery/mockery|0.9.4
monolog/monolog|1.17.2
mtdowling/cron-expression|v1.0.4
mtdowling/jmespath.php|2.2.0
namshi/jose|5.0.2
nesbot/carbon|1.20.0
nikic/php-parser|v1.4.1
paragonie/random_compat|1.0.5
phpdocumentor/reflection-docblock|2.0.4
phpseclib/phpseclib|0.3.10
phpspec/php-diff|v1.0.2
phpspec/phpspec|2.3.0
phpspec/prophecy|v1.5.0
phpunit/php-code-coverage|2.2.4
phpunit/php-file-iterator|1.4.1
phpunit/php-text-template|1.2.1
phpunit/php-timer|1.0.7
phpunit/php-token-stream|1.4.8
phpunit/phpunit|4.8.13
phpunit/phpunit-mock-objects|2.3.8
predis/predis|v1.0.3
psr/http-message|1.0
psr/log|1.0.0
psy/psysh|v0.5.2
sebastian/comparator|1.2.0
sebastian/diff|1.3.0
sebastian/environment|1.3.2
sebastian/exporter|1.2.1
sebastian/global-state|1.1.1
sebastian/recursion-context|1.0.1
sebastian/version|1.0.6
swiftmailer/swiftmailer|v5.4.1
symfony/console|v2.7.5
symfony/css-selector|v2.7.5
symfony/debug|v2.7.5
symfony/dom-crawler|v2.7.5
symfony/event-dispatcher|v2.7.5
symfony/finder|v2.7.5
symfony/http-foundation|v2.7.5
symfony/http-kernel|v2.7.5
symfony/process|v2.7.5
symfony/routing|v2.7.5
symfony/translation|v2.7.5
symfony/var-dumper|v2.7.5
symfony/yaml|v2.7.5
tymon/jwt-auth|0.5.5
vlucas/phpdotenv|v1.1.1
yajra/laravel-datatables-oracle|v5.11.10

**routes.php**
```php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    $customClaims = ['company_id' => '9'];

    $payload = JWTFactory::make($customClaims);

    $token = JWTAuth::encode($payload);
    return $token;
});

//Route::group([],function(){
Route::group(['middleware'=>'jwt.auth'],function(){
    $controllers = array(
        'AnnouncementController' => array(
            'resource'      => 'announcement',
            'custom_urls'   => array(
                'announcement/codes'            => 'AnnouncementController@codes',
                'announcement/{id}/codes'       => 'AnnouncementController@codes',
                'announcement/{id}/{relation}'  => 'AnnouncementController@getRelation',
            )
        ),
        'AppTypeController' => array(
            'resource'  => 'app/type',
        ),
        'AppController' => array(
            'resource'  => 'app',
        ),
        'BlacklistController'   => array(
            'resource'  => 'blacklist',
        ),
        'CitylookupController'  => array(
            'resource'  => 'citylookup',
        ),
        'CompanyController' => array(
            'resource'      => 'company',
            'custom_urls'   => array(
                'company/{company_id}/invoice/'                 => 'CompanyInvoiceController@index',
                'company/{company_id}/invoice/{invoice_id}'     => array(
                    'method'        => 'GET',
                    'controller'    => 'CompanyInvoiceController@show',
                ),
                /*
                'company/{company_id}/invoice/{invoice_id}'     => array(
                    'method'        => 'POST',
                    'CompanyInvoiceController@index',
                ),
                'company/{company_id}/invoice/{invoice_id}'     => array(
                    'method'        => 'GET',
                    'CompanyInvoiceController@index',
                ),
                */
            )
        ),
        'ExtensionController' => array(
            'resource'      => 'extension',
        ),
        /*'CdrController' => array(
            'resource'      => 'cdr',
        ),*/

    );

    foreach($controllers as $controller => $cdata){
        if(isset($cdata['custom_urls'])){
            foreach($cdata['custom_urls'] as $url => $route){
                if(isset($route['method'])){
                    if($route['method'] == 'GET') {
                        Route::get($url, $route['controller']);
                    } else if($route['method'] == 'PATCH'){
                        Route::patch($url, $route['controller']);
                    } else if($route['method'] == 'POST'){
                        Route::post($url, $route['controller']);
                    } else if($route['method'] == 'PUT'){
                        Route::put($url, $route['controller']);
                    } else if($route['method'] == 'DELETE'){
                        Route::delete($url, $route['controller']);
                    }
                } else {
                    Route::get($url, $route);
                }
            }
        }
        if(isset($cdata['resource'])){
            Route::resource($cdata['resource'],$controller);
        }
    }
});
```
**Kernel.php**
```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        //\App\Http\Middleware\VerifyCsrfToken::class,
    ];

    /**
     * The application's route middleware.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
        'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,
    ];
}
```

config/app.php
```<?php
...
    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Routing\ControllerServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        /*
         * Custom Macro Service Provider
         */
        App\Providers\MacroServiceProvider::class,

        /*
         * JWT Service Provider
         */
        Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,

        /*
         * Laravel-CORS Service Provider
         */
        Barryvdh\Cors\ServiceProvider::class,

        /*
         * Custom Callbacks Service Provider
         */
        App\Providers\CallbackServiceProvider::class,

        /*
         * Laravel Datatables Service Provider
         */
        yajra\Datatables\DatatablesServiceProvider::class,

    ],
...
    'aliases' => [

        'App'       => Illuminate\Support\Facades\App::class,
        'Artisan'   => Illuminate\Support\Facades\Artisan::class,
        'Auth'      => Illuminate\Support\Facades\Auth::class,
        'Blade'     => Illuminate\Support\Facades\Blade::class,
        'Bus'       => Illuminate\Support\Facades\Bus::class,
        'Cache'     => Illuminate\Support\Facades\Cache::class,
        'Config'    => Illuminate\Support\Facades\Config::class,
        'Cookie'    => Illuminate\Support\Facades\Cookie::class,
        'Crypt'     => Illuminate\Support\Facades\Crypt::class,
        'DB'        => Illuminate\Support\Facades\DB::class,
        'Eloquent'  => Illuminate\Database\Eloquent\Model::class,
        'Event'     => Illuminate\Support\Facades\Event::class,
        'File'      => Illuminate\Support\Facades\File::class,
        'Hash'      => Illuminate\Support\Facades\Hash::class,
        'Input'     => Illuminate\Support\Facades\Input::class,
        'Inspiring' => Illuminate\Foundation\Inspiring::class,
        'Lang'      => Illuminate\Support\Facades\Lang::class,
        'Log'       => Illuminate\Support\Facades\Log::class,
        'Mail'      => Illuminate\Support\Facades\Mail::class,
        'Password'  => Illuminate\Support\Facades\Password::class,
        'Queue'     => Illuminate\Support\Facades\Queue::class,
        'Redirect'  => Illuminate\Support\Facades\Redirect::class,
        'Redis'     => Illuminate\Support\Facades\Redis::class,
        'Request'   => Illuminate\Support\Facades\Request::class,
        'Response'  => Illuminate\Support\Facades\Response::class,
        'Route'     => Illuminate\Support\Facades\Route::class,
        'Schema'    => Illuminate\Support\Facades\Schema::class,
        'Session'   => Illuminate\Support\Facades\Session::class,
        'Storage'   => Illuminate\Support\Facades\Storage::class,
        'URL'       => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View'      => Illuminate\Support\Facades\View::class,

        /*
         * JWT Auth
         */
        'JWTAuth' => Tymon\JWTAuth\Facades\JWTAuth::class,
        'JWTFactory' => Tymon\JWTAuth\Facades\JWTFactory::class,

        /*
         * Laravel Datatables
         */
        'Datatables' => yajra\Datatables\Datatables::class,
    ],

];

```

**Comment by tdhsmith** [comment]
What Laravel version did you upgrade _from_? And perhaps a silly question: have you tried running `composer dump-autoload`? I know my autoload/bootstrap stuff always gets funky after an update.

**Comment by Destreyf** [comment]
@tdhsmith Thank you very much for mentioning dump-autoload, this fixed my issue.

I was on Laravel 5.1.4

**Comment by tdhsmith** [comment]
At this point I run that command all the time, haha. In theory, it should only be necessary when you're adding and removing classes, but I've seen it fix mysterious stuff.

**Comment by csprocket777** [comment]
What does your routes entry look like for the refresh endpoint?

**Comment by EwanValentine** [comment]
I'm still getting 
```
ReflectionException in Container.php line 741:
Class Tymon\JWTAuth\Providers\JWT\Namshi does not exist
```

**Comment by hetunandu** [comment]
I am getting this error too! Any solutions?

**Comment by Destreyf** [comment]
The solution for my issue was to this to run composer dump-autoload, this fixes the dependency issues for me.

As for the error Ewan is getting, i have not run into this, if you're having this issue you should open a new issue (as this one was resolved/closed).

**Comment by hetunandu** [comment]
I solved it buy deleting the JWT config file and publishing a new config file. The problem was that the class names had changed.

**Comment by v3rron** [comment]
still having this issue, even after deleting `jwt.php` file from `config` folder and running:
```
php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
php artisan jwt:generate
composer dump
```
everything is configured. Middleware is only working for me from Controller __construct function:
```
public function __construct()
{
    $this->middleware('jwt.auth');
}
```
but not working when set in routes.php:
```
Route::group(['middleware' => 'jwt-auth'], function() {
    Route::get('test', 'AuthController@test');
});
```

**Comment by tdhsmith** [comment]
You're using the different middleware names there: `jwt-auth` in the group definition and `jwt.auth` in your controller. (hyphen vs period)

**Comment by v3rron** [comment]
OMG thank you. That was it.
