### ISSUE TITLE
Issues installation " Conclusion: remove phpseclib/phpseclib 2.0.1"

### ISSUE THREAD

**Issue by jycr753** [tymondesigns/jwt-auth#675]
Hey I keep getting this error when I install try to install

 ```
Problem 1
    - Conclusion: remove phpseclib/phpseclib 2.0.1
    - Installation request for tymon/jwt-auth ^0.5.9 -> satisfiable by tymon/jwt-auth[0.5.9].
    - Conclusion: don't install phpseclib/phpseclib 0.3.10
    - Conclusion: don't install phpseclib/phpseclib 2.0.1|install phpseclib/phpseclib 0.3.10
    - tymon/jwt-auth 0.5.9 requires namshi/jose 5.0.* -> satisfiable by namshi/jose[5.0.0, 5.0.1, 5.0.2].
    - namshi/jose 5.0.0 requires phpseclib/phpseclib ~0.3 -> satisfiable by phpseclib/phpseclib[0.3.0, 0.3.1, 0.3.10, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9].
    - namshi/jose 5.0.1 requires phpseclib/phpseclib ~0.3 -> satisfiable by phpseclib/phpseclib[0.3.0, 0.3.1, 0.3.10, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9].
    - namshi/jose 5.0.2 requires phpseclib/phpseclib ~0.3 -> satisfiable by phpseclib/phpseclib[0.3.0, 0.3.1, 0.3.10, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9].
    - Can only install one of: phpseclib/phpseclib[0.3.0, 2.0.1].
    - Can only install one of: phpseclib/phpseclib[0.3.1, 2.0.1].
    - Can only install one of: phpseclib/phpseclib[0.3.5, 2.0.1].
    - Can only install one of: phpseclib/phpseclib[0.3.6, 2.0.1].
    - Can only install one of: phpseclib/phpseclib[0.3.7, 2.0.1].
    - Can only install one of: phpseclib/phpseclib[0.3.8, 2.0.1].
    - Can only install one of: phpseclib/phpseclib[0.3.9, 2.0.1].
    - Installation request for phpseclib/phpseclib == 2.0.1.0 -> satisfiable by phpseclib/phpseclib[2.0.1].

```

**Comment by GrahamCampbell** [comment]
You need to upgrade to namshi/jose 6.x or 7.x.

**Comment by GrahamCampbell** [comment]
No bug. This package already uses 6.x. Conclusion: you are trying to install, an out of date version of this package.

**Comment by GrahamCampbell** [comment]
Make sure you use the latest dev version of this, and not the alpha one.

**Comment by jycr753** [comment]
Yes you are right, looks like one packages have as decencies the same library with different versions...

**Comment by jycr753** [comment]
Because when I do that I get this: 

```
Problem 1
    - Installation request for tymon/jwt-auth ^0.5.9 -> satisfiable by tymon/jwt-auth[0.5.9].
    - tymon/jwt-auth 0.5.9 requires namshi/jose 5.0.* -> satisfiable by namshi/jose[5.0.0, 5.0.1, 5.0.2] but these conflict with your requirements or minimum-stability


```

**Comment by jycr753** [comment]
My required packages are:

```
"php": ">=5.5.9",
	"laravel/framework": "5.2.*",
	"intervention/image": "^2.3.1",
	"jenssegers/agent": "v2.1.7",
	"namshi/jose": "6.*",
	"rcrowe/twigbridge": "^0.9.1",
	"barryvdh/laravel-dompdf": "0.6.*",
	"toin0u/geotools-laravel": "~1.0",
	"toin0u/geocoder-laravel": "@stable",
	"bugsnag/bugsnag-laravel": "1.*",
	"pda/pheanstalk": "3.0.*",
	"googleads/googleads-php-lib": "6.2.*",
	"indatus/dispatcher": "1.*",
	"doctrine/dbal": "^2.5",
	"laracasts/testdummy": "~2.3.2",
	"predis/predis": "~1.0",
	"kryptonit3/pusher": "dev-master",
    "shooka/laravel-modelevents": "^0.2.0",
    "dingo/api": "1.0.x@dev",
	"laravelcollective/remote": "5.2.*"
```

**Comment by jycr753** [comment]
And the full error is: 
```

composer require tymon/jwt-auth --sort-packages --prefer-source --update-no-dev
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^0.5.9 for tymon/jwt-auth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tymon/jwt-auth ^0.5.9 -> satisfiable by tymon/jwt-auth[0.5.9].
    - tymon/jwt-auth 0.5.9 requires namshi/jose 5.0.* -> satisfiable by namshi/jose[5.0.0, 5.0.1, 5.0.2] but these conflict with your requirements or minimum-stability


Installation failed, reverting ./composer.json to its original content.
```

**Comment by jycr753** [comment]
and if I try to install 	`"namshi/jose": "dev-master",` still get the same error:

```
Problem 1
    - Installation request for tymon/jwt-auth ^0.5.9 -> satisfiable by tymon/jwt-auth[0.5.9].
    - tymon/jwt-auth 0.5.9 requires namshi/jose 5.0.* -> satisfiable by namshi/jose[5.0.0, 5.0.1, 5.0.2] but these conflict with your requirements or minimum-stability

```

**Comment by shooka** [comment]
It is because the `laravelcollective/remote` package uses a newer version of `phpseclib` than `jwt-auth` does. The `composer.json` should be updated to use the newest stable version of `namshi/jose`.

**Comment by shooka** [comment]
#679

**Comment by ErvinLlojku** [comment]
@shooka You are right. @tymondesigns needs to update the package dependencies.

**Comment by shooka** [comment]
@ErvinLlojku It seems to have been fixed in #681. Now we just need this to be released.

**Comment by jycr753** [comment]
Yes all will be fixed, we hope it doesn't #Campbell on us

**Comment by jycr753** [comment]
All works properly now in alpha 👍

**Comment by yarcowang** [comment]
The wiki still... https://github.com/tymondesigns/jwt-auth/wiki/Installation

**Comment by aftabnaveed** [comment]
I know this issue is closed. I did install the latest version namshi.jose 7.2.3, but still my dependencies are not resolved. Here is what I get.

```bash
Using version ^0.5.11 for tymon/jwt-auth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tymon/jwt-auth ^0.5.11 -> satisfiable by tymon/jwt-auth[0.5.11].
    - Conclusion: remove namshi/jose 7.2.3
    - Conclusion: don't install namshi/jose 7.2.3
    - tymon/jwt-auth 0.5.11 requires namshi/jose 5.0.* -> satisfiable by namshi/jose[5.0.0, 5.0.1, 5.0.2].
    - Can only install one of: namshi/jose[5.0.0, 7.2.3].
    - Can only install one of: namshi/jose[5.0.1, 7.2.3].
    - Can only install one of: namshi/jose[5.0.2, 7.2.3].
    - Installation request for namshi/jose (locked at 7.2.3) -> satisfiable by namshi/jose[7.2.3].


Installation failed, reverting ./composer.json to its original content.

```

**Comment by aftabnaveed** [comment]
OK I was able to fix it by requiring ```"tymon/jwt-auth": "1.0.0-beta.3"```

**Comment by webfelipemaia** [comment]
@aftabnaveed Thanks!
Worked for me!

**Comment by manjiriparab** [comment]
hello i'm just upgrading laravel from 5.8 to 6 and in my composer namshi/jose this package is not mentioned yet while updating composer i got error
`Problem 1
    - namshi/jose 5.0.2 requires phpseclib/phpseclib ~0.3 -> no matching package found.
    - namshi/jose 5.0.1 requires phpseclib/phpseclib ~0.3 -> no matching package found.
    - namshi/jose 5.0.0 requires phpseclib/phpseclib ~0.3 -> no matching package found.
`
